name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
      - run: zig build test
      - run: zig fmt --check src/

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        target:
          - x86_64-linux
          - aarch64-linux
          - x86_64-macos
          - aarch64-macos
        optimize:
          - Debug
          - ReleaseSafe

    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
        with:
          version: master
      - name: Build ${{ matrix.target }} (${{ matrix.optimize }})
        run: |
          zig build -Doptimize=${{ matrix.optimize }} -Dtarget=${{ matrix.target }}

      - name: Verify binary
        if: matrix.target == 'x86_64-linux'
        run: |
          ./zig-out/bin/cm --help
          file zig-out/bin/cm
